<?php
include('../dbconfig/dbcon.php');
$conn = dbcon();
session_start();


$date = $_POST["txtdate"];
$subject = $_POST["txtsubject"];
$description = $_POST["txtdescription"];
$sessionpersone = $_POST["txtsessionpersone"];
$ticketid = $_POST["txtticketid"];


if (mysqli_query($conn, "insert into tbl_helpdesk(Ticketid,date,subject,description,createdby,createddate,status) 
			values('$ticketid','$date','$subject','$description','$sessionpersone',NOW(),0)")) {
	mysqli_query($conn,"insert into tbl_audit(message,action,updatePerson,date) values(' TICKET ID $ticketid Generated By $sessionpersone','adding','$sessionpersone',NOW())");
	echo "<script>
				alert('Ticket Added Successfully...!!');
				window.location='frmhelpdesk.php';
				</script>";
} else {
	echo "<script>
				alert('Ticket Not  Added.Please Check Again!!');
				window.location='frmhelpdesk.php';
				</script>";
}
