<?php 
 session_start();
 if(!isset($_SESSION['SESS_MEMBER_NAME']))
 {
	 echo "<script>window.location='http://drmpsur-hrms.in/e-apar/index.php';</script>";
 }
include_once('../global/header.php');
include_once('../global/topbar.php');
include_once('../global/sidebaradmin.php');

?>
<script>
//----------------------------// Document Ready Function //----------------------------//
		$(document).ready(function ()
		{
		ShowRecordsUser();
		 $("#frmaddemployee").submit(function(event)
		{
			var formData = new FormData($(this)[0]);
			formData.append("Flag",$("#btnSave").val());
			$.ajax({
				url: "Ajaxemployee.php",
				type: 'POST',
				data: formData,
				async: false,
				success: function (data) {
					// alert(data);
					// ShowRecords();
				},
				cache: false,
				contentType: false,
				processData: false
			});
		});
		});///ready fun close


//----------------------------//Function ShowRecords User//----------------------------//
function ShowRecordsUser()
{
	$.post("Ajaxemployee.php",
				{
					Flag:"ShowRecordsUser"
				},
					function(data,success)
					{
						$("#divRecords").html(data);
						var oTable = $('#example').dataTable
						({
							"oLanguage":
							{
								"sSearch": "Search all columns:"
							},
							"aoColumnDefs":
							[
								{
									'bSortable': false,
									'aTargets': [0]
								} //disables sorting for column one
							],
							'iDisplayLength': 12,
							"sPaginationType": "full_numbers",
							"dom": 'T<"clear">lfrtip'
						});
					}
			);
}
//----------------------------End Of Script--------------------------------------//
</script> 

<style>
.primary
{
	 box-shadow: none;
	border-color: rgba(60, 141, 188, 0.53);
}
</style>
 <!-- Left side column. contains the logo and sidebar -->
 <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1> Helpdesk </h1> 
    </section>
	
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box-body pad">
                    <form action="Ajaxhelpdesk.php" method="POST" action="" enctype="multipart/form-data" role="form" id="frmhelpdesk">
			            <div class="box box-warning box-solid" style="margin-top:0px;">
            				<div class="box-header with-border">
            				    <h3 class="box-title"><i class="fa fa-eye"></i> &nbsp;&nbsp;View Requests...</h3>
            				</div>
				            <div class="table-responsive p-12">
                                <table class="table table-bordered no-margin" id="example">
                                    <thead>
                                        <tr>
                        				    <th>Date</th>
                                            <th>TICKET ID</th>
                                            <th>Subject</th>
                                            <th>Descrption</th>
                                            <th>Generated By</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead> 
				                    <tbody>
                        				<?php
                        				$sqlquery=mysqli_query($conn,"select * from tbl_helpdesk where status=0");
                        				while($rwReg=mysqli_fetch_array($sqlquery))
                        				{
                        				$id=$rwReg["HLP_id"];
                        				//echo "$id";
                        				?>
                        				<tr>
                        				<td><?php echo date('d-m-Y', strtotime($rwReg["date"]));?></td>
                        				<td><?php echo $rwReg["Ticketid"]; ?></td>
                        				<td><?php echo $rwReg["subject"];?></td>
                        				<td><?php echo $rwReg["description"];?></td>
                        				<td><?php echo $rwReg["createdby"];?></td>
                        				<td><?php echo '<a href="Viewhelpdesk.php?HLP_id='.$id.'" class="btn btn-warning btn-flat"><i class="fa fa-edit"></i> Pending</a>';?></td>
                        				</tr>
                        				<?php
                        				
                        				}
				                        ?>
				                    </tbody> 
                                </table>
                            </div>
                        </div>
			            <div class="clearfix"></div> 
                    </form>
			    </div>
            </div> 
    		<div class="col-md-12">
    			<div class="box-body pad">
    			    <form action="" method="POST" action="" enctype="multipart/form-data" role="form" id="">
    					<div class="box box-success box-solid" style="margin-top:0px;">
    						<div class="box-header with-border">
    						    <h3 class="box-title"><i class="fa fa-check"></i> &nbsp;&nbsp;Approved Requests...</h3>
    						</div>
    						<div class="table-responsive p-12">
    							<table class="table table-bordered no-margin" id="example">
        							<thead>
        							    <tr>
                							<th>Date</th>
                							<th>TICKET ID</th>
                						    <th>Subject</th>
                							<th>Descrption</th>
                							<th>Generated By</th>
                							<th>View</th>
        							    </tr>
    							    </thead> 
    						        <tbody>
            							  <?php
                							$sqlquery=mysqli_query($conn,"select * from tbl_helpdesk where status=1");
                							while($rwReg=mysqli_fetch_array($sqlquery))
                							{
                							$id=$rwReg["HLP_id"];
                							//echo "$id";
                							?>
                							<tr>
                							<td><?php echo date('d-m-Y', strtotime($rwReg["date"]));?></td>
                							<td><?php echo $rwReg["Ticketid"]; ?></td>
                							<td><?php echo $rwReg["subject"];?></td>
                							<td><?php echo $rwReg["description"];?></td>
                							<td><?php echo $rwReg["createdby"];?></td>
                							<!--td><?php echo '<a href="Viewhelpdesk.php?HLP_id=".$id."" class="btn btn-success btn-flat"><i class="fa fa-check"></i> Approved</a>'?></td-->
                							<td><?php echo '<span class="btn btn-success btn-flat"><i class="fa fa-check"></i> Approved</span>'?></td>
                							
                							</tr>
                							<?php
                							
                							}
                							?>
        							</tbody> 
    						    </table>
    					    </div>
    					</div>
    			    </form>
    			</div>
    		</div> 
	    </div> 
    </section>
    <!-- /.content -->
  </div>
 
   <?php
 include_once('../global/footer.php');
 ?> 