<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>

<body>
&lt;option  value='1' &gt;WADI&lt;/option&gt;<br />
&lt;option  value='2' &gt;SHAHABAD&lt;/option&gt;<br />
&lt;option  value='3' &gt;MARTUR&lt;/option&gt;<br />
&lt;option  value='4' &gt;HIRENANDURU&lt;/option&gt;<br />
&lt;option  value='5' &gt;GULBARGA&lt;/option&gt;<br />
&lt;option  value='6' &gt;BABLAD&lt;/option&gt;<br />
&lt;option  value='7' &gt;SAVALGI&lt;/option&gt;<br />
&lt;option  value='8' &gt;HUNSIHADGIL&lt;/option&gt;<br />
&lt;option  value='9' &gt;GANGAPUR ROAD&lt;/option&gt;<br />
&lt;option  value='10' &gt;GAUDGAON&lt;/option&gt;<br />
&lt;option  value='11' &gt;KULALI&lt;/option&gt;<br />
&lt;option  value='12' &gt;DUDHANI&lt;/option&gt;<br />
&lt;option  value='13' &gt;BOROTI&lt;/option&gt;<br />
&lt;option  value='14' &gt;NAGANSUR&lt;/option&gt;<br />
&lt;option  value='15' &gt;AKALKOT ROAD&lt;/option&gt;<br />
&lt;option  value='16' &gt;TILATI&lt;/option&gt;<br />
&lt;option  value='17' &gt;HOTGI&lt;/option&gt;<br />
&lt;option  value='18' &gt;TIKEKARWADI&lt;/option&gt;<br />
&lt;option  value='19' &gt;SOLAPUR&lt;/option&gt;<br />
&lt;option  value='20' &gt;BALE&lt;/option&gt;<br />
&lt;option  value='21' &gt;PAKNI&lt;/option&gt;<br />
&lt;option  value='22' &gt;MUNDHEWADI&lt;/option&gt;<br />
&lt;option  value='23' &gt;MOHOL&lt;/option&gt;<br />
&lt;option  value='24' &gt;MALIKPETH&lt;/option&gt;<br />
&lt;option  value='25' &gt;ANGAR&lt;/option&gt;<br />
&lt;option  value='26' &gt;VAKAV&lt;/option&gt;<br />
&lt;option  value='27' &gt;MADHA&lt;/option&gt;<br />
&lt;option  value='28' &gt;WADSINGE&lt;/option&gt;<br />
&lt;option  value='29' &gt;KURDUWADI&lt;/option&gt;<br />
&lt;option  value='30' &gt;DHAVLAS&lt;/option&gt;<br />
&lt;option  value='31' &gt;KEM&lt;/option&gt;<br />
&lt;option  value='32' &gt;BHALWANI&lt;/option&gt;<br />
&lt;option  value='33' &gt;JEUR&lt;/option&gt;<br />
&lt;option  value='34' &gt;POPHLAJ&lt;/option&gt;<br />
&lt;option  value='35' &gt;WASHIMBE&lt;/option&gt;<br />
&lt;option  value='36' &gt;PAREWADI&lt;/option&gt;<br />
&lt;option  value='37' &gt;JINTI ROAD&lt;/option&gt;<br />
&lt;option  value='38' &gt;BHIGVAN&lt;/option&gt;<br />
&lt;option  value='39' &gt;MALTHAN&lt;/option&gt;<br />
&lt;option  value='40' &gt;BORIBAIL&lt;/option&gt;<br />
&lt;option  value='41' &gt;DAUND&lt;/option&gt;<br />
&lt;option  value='42' &gt;KASHTI&lt;/option&gt;<br />
&lt;option  value='43' &gt;SHRIGONDA ROAD&lt;/option&gt;<br />
&lt;option  value='44' &gt;BELVANDI&lt;/option&gt;<br />
&lt;option  value='45' &gt;VISAPUR&lt;/option&gt;<br />
&lt;option  value='46' &gt;RANJANGAON ROAD&lt;/option&gt;<br />
&lt;option  value='47' &gt;SAROLA&lt;/option&gt;<br />
&lt;option  value='48' &gt;AKOLNAR&lt;/option&gt;<br />
&lt;option  value='49' &gt;AHMEDNAGAR&lt;/option&gt;<br />
&lt;option  value='50' &gt;NIMBLAK&lt;/option&gt;<br />
&lt;option  value='51' &gt;VILAD&lt;/option&gt;<br />
&lt;option  value='52' &gt;VAMBORI&lt;/option&gt;<br />
&lt;option  value='53' &gt;RAHURI&lt;/option&gt;<br />
&lt;option  value='54' &gt;TAKLIMIYA&lt;/option&gt;<br />
&lt;option  value='55' &gt;PADHEGAON&lt;/option&gt;<br />
&lt;option  value='56' &gt;NIPANI VADGAON&lt;/option&gt;<br />
&lt;option  value='57' &gt;BELAPUR&lt;/option&gt;<br />
&lt;option  value='58' &gt;CHITALI&lt;/option&gt;<br />
&lt;option  value='59' &gt;PUNTAMBA&lt;/option&gt;<br />
&lt;option  value='60' &gt;KANHEGAON&lt;/option&gt;<br />
&lt;option  value='61' &gt;SAVANSTSAR&lt;/option&gt;<br />
&lt;option  value='62' &gt;KOPARGAON&lt;/option&gt;<br />
&lt;option  value='63' &gt;YEOLA&lt;/option&gt;<br />
&lt;option  value='64' &gt;LAUL&lt;/option&gt;<br />
&lt;option  value='65' &gt;MODLIMB&lt;/option&gt;<br />
&lt;option  value='66' &gt;ASHTI&lt;/option&gt;<br />
&lt;option  value='67' &gt;BABHULGAON&lt;/option&gt;<br />
&lt;option  value='68' &gt;PANDHARPUR&lt;/option&gt;<br />
&lt;option  value='69' &gt;LATUR&lt;/option&gt;<br />
&lt;option  value='70' &gt;BARSI TOWN&lt;/option&gt;<br />
&lt;option  value='71' &gt;BOHALI&lt;/option&gt;<br />
&lt;option  value='72' &gt;BAMANI&lt;/option&gt;<br />
&lt;option  value='73' &gt;SANGOLA&lt;/option&gt;<br />
&lt;option  value='74' &gt;WASUD&lt;/option&gt;<br />
&lt;option  value='75' &gt;JAVALA&lt;/option&gt;<br />
&lt;option  value='76' &gt;JATH ROAD&lt;/option&gt;<br />
&lt;option  value='77' &gt;GULVANCHI&lt;/option&gt;<br />
&lt;option  value='78' &gt;DHALGAON&lt;/option&gt;<br />
&lt;option  value='79' &gt;LANGERPETH&lt;/option&gt;<br />
&lt;option  value='80' &gt;KAVATHE MAHANKAL&lt;/option&gt;<br />
&lt;option  value='81' &gt;AGRAN DHULGAON&lt;/option&gt;<br />
&lt;option  value='82' &gt;SALAGRE&lt;/option&gt;<br />
&lt;option  value='83' &gt;BELANKI&lt;/option&gt;<br />
&lt;option  value='84' &gt;ARAG&lt;/option&gt;<br />
&lt;option  value='85' &gt;BOLWAD&lt;/option&gt;<br />
&lt;option  value='86' &gt;MIRAJ&lt;/option&gt;<br />
&lt;option  value='87' &gt;ARAG&lt;/option&gt;<br />
&lt;option  value='88' &gt;URULI&lt;/option&gt;<br />
&lt;option  value='89' &gt;PUNE&lt;/option&gt;<br />
&lt;option  value='90' &gt;BHUSAVAL&lt;/option&gt;<br />
&lt;option  value='91' &gt;ANKAI&lt;/option&gt;<br />
&lt;option  value='92' &gt;CHINK HILL&lt;/option&gt;<br />
&lt;option  value='93' &gt;JEUR&lt;/option&gt;<br />
&lt;option  value='94' &gt;LONI&lt;/option&gt;<br />
&lt;option  value='95' &gt;NIPANI WADGAON&lt;/option&gt;<br />
&lt;option  value='96' &gt;SCHENDRI&lt;/option&gt;<br />
&lt;option  value='97' &gt;RAICHUR&lt;/option&gt;<br />
&lt;option  value='98' &gt;WARKUTE&lt;/option&gt;<br />
&lt;option  value='99' &gt;CHOWDAPUR&lt;/option&gt;<br />
&lt;option  value='100' &gt;DHOKY&lt;/option&gt;<br />
&lt;option  value='101' &gt;HARANGUL&lt;/option&gt;<br />
&lt;option  value='102' &gt;KUSALAMB&lt;/option&gt;<br />
&lt;option  value='103' &gt;KALAMB ROAD&lt;/option&gt;<br />
&lt;option  value='104' &gt;SAINAGAR&lt;/option&gt;<br />
&lt;option  value='105' &gt;MAHISGAON&lt;/option&gt;<br />
&lt;option  value='106' &gt;NIVALI&lt;/option&gt;<br />
&lt;option  value='107' &gt;AUSA ROAD&lt;/option&gt;<br />
&lt;option  value='108' &gt;PALSAP&lt;/option&gt;<br />
&lt;option  value='109' &gt;PANGRI&lt;/option&gt;<br />
&lt;option  value='110' &gt;PADASALI&lt;/option&gt;<br />
&lt;option  value='111' &gt;RAMLING&lt;/option&gt;<br />
&lt;option  value='112' &gt;THER&lt;/option&gt;<br />
&lt;option  value='113' &gt;UPALAI&lt;/option&gt;<br />
&lt;option  value='114' &gt;YEDASHI&lt;/option&gt;<br />
&lt;option  value='115' &gt;LATUR ROAD&lt;/option&gt;<br />
&lt;option  value='116' &gt;GHARNI&lt;/option&gt;<br />
&lt;option  value='117' &gt;BHATANGALI&lt;/option&gt;<br />
&lt;option  value='118' &gt;USMANABAD&lt;/option&gt;<br />
&lt;option  value='119' &gt;MURUD&lt;/option&gt;
</body>
</html>
